class RecentFile {
  final String? icon, title, date, size,size1,size2,size3,size4,size5,size6,size7,size8,size9,size10;

  RecentFile({this.icon, this.title, this.date, this.size,this.size1,this.size2,this.size3,this.size4,this.size5,this.size6,this.size7,this.size8,this.size9,this.size10});
}

List demoRecentFiles = [
  RecentFile(
    icon: "assets/icons/xd_file.svg",
    title: "XD File",
    date: "01-03-2021",
    size: "3.5mb",
    size1: "3.5mb",
    size2: "3.5mb",
    size3: "3.5mb",
    size4: "3.5mb",
    size5: "XD File",
    size6: "XD File",
    size7: "XD File",
    size8: "XD File",
    size9: "XD File",
    size10: "XD File",
  ),
  RecentFile(
    icon: "assets/icons/Figma_file.svg",
    title: "Figma File",
    date: "27-02-2021",
    size: "19.0mb",
    size1: "3.5mb",
    size2: "3.5mb",
    size3: "3.5mb",
    size4: "3.5mb",
    size5: "XD File",
    size6: "XD File",
    size7: "XD File",
    size8: "XD File",
    size9: "XD File",
    size10: "XD File",
  ),
  RecentFile(
    icon: "assets/icons/doc_file.svg",
    title: "Document",
    date: "23-02-2021",
    size: "32.5mb",
    size1: "3.5mb",
    size2: "3.5mb",
    size3: "3.5mb",
    size4: "3.5mb",
    size5: "XD File",
    size6: "XD File",
    size7: "XD File",
    size8: "XD File",
    size9: "XD File",
    size10: "XD File",
  ),
  RecentFile(
    icon: "assets/icons/sound_file.svg",
    title: "Sound File",
    date: "21-02-2021",
    size: "3.5mb",
    size1: "3.5mb",
    size2: "3.5mb",
    size3: "3.5mb",
    size4: "3.5mb",
    size5: "XD File",
    size6: "XD File",
    size7: "XD File",
    size8: "XD File",
    size9: "XD File",
    size10: "XD File",
  ),
  RecentFile(
    icon: "assets/icons/media_file.svg",
    title: "Media File",
    date: "23-02-2021",
    size: "2.5gb",
    size1: "3.5mb",
    size2: "3.5mb",
    size3: "3.5mb",
    size4: "3.5mb",
    size5: "XD File",
    size6: "XD File",
    size7: "XD File",
    size8: "XD File",
    size9: "XD File",
    size10: "XD File",
  ),
  RecentFile(
    icon: "assets/icons/pdf_file.svg",
    title: "Sales PDF",
    date: "25-02-2021",
    size: "3.5mb",
    size1: "3.5mb",
    size2: "3.5mb",
    size3: "3.5mb",
    size4: "3.5mb",
    size5: "XD File",
    size6: "XD File",
    size7: "XD File",
    size8: "XD File",
    size9: "XD File",
    size10: "XD File",
  ),
  RecentFile(
    icon: "assets/icons/excle_file.svg",
    title: "Excel File",
    date: "25-02-2021",
    size: "34.5mb",
    size1: "3.5mb",
    size2: "3.5mb",
    size3: "3.5mb",
    size4: "3.5mb",
    size5: "XD File",
    size6: "XD File",
    size7: "XD File",
    size8: "XD File",
    size9: "XD File",
    size10: "XD File",
  ),
];
